// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Microsoft_DetailVideos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMicrosoft_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		EntitiesBase.YouTubeVideo CurrentYouTubeVideo { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaMicrosoft_DetailVideos0 property.
        /// </summary>
		bool HasNextpanoramaMicrosoft_DetailVideos0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaMicrosoft_DetailVideos0 property.
        /// </summary>
		bool HasPreviouspanoramaMicrosoft_DetailVideos0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechMicrosoft_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechMicrosoft_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareMicrosoft_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand ShareMicrosoft_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartMicrosoft_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartMicrosoft_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceMicrosoft_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceMicrosoft_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaMicrosoft_DetailVideos0 command.
        /// </summary>
		ICommand NextpanoramaMicrosoft_DetailVideos0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaMicrosoft_DetailVideos0 command.
        /// </summary>
		ICommand PreviouspanoramaMicrosoft_DetailVideos0 { get; }

	}
}
