// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Microsoft_Videos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMicrosoft_VideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the Microsoft_VideosListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.YouTubeVideo> Microsoft_VideosListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Microsoft_VideosListControlCollectionPageNumber property.
        /// </summary>
		int Microsoft_VideosListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedMicrosoft_VideosListControlCollection property.
        /// </summary>
		EntitiesBase.YouTubeVideo SelectedMicrosoft_VideosListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the CurrentAboutTheseChannels_InfoHtmlControl property.
        /// </summary>
		string CurrentAboutTheseChannels_InfoHtmlControl { get; set; }
        
        /// <summary>
        /// Gets the RefreshMicrosoft_VideosListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshMicrosoft_VideosListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetMicrosoft_VideosListControlCollectionCommand command.
        /// </summary>
		ICommand GetMicrosoft_VideosListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechAboutTheseChannels_InfoHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechAboutTheseChannels_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareAboutTheseChannels_InfoHtmlControlCommand command.
        /// </summary>
		ICommand ShareAboutTheseChannels_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartAboutTheseChannels_InfoHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartAboutTheseChannels_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
